---
title: Terminal Times
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: An Open Comedy Publication
baseurl: ''
url: http://terminaltimes.com
permalink: "/:year/:title"
email: evan.m.wall@gmail.com
disqus-id: ''
headerimage: "/images/terminaltimes.jpg"
markdown: kramdown
sass:
  style: :compressed
