---
title: Terminal Times
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: An Open Comedy Publication
baseurl: ''
url: http://terminaltimes.com
permalink: "/:year/:title"
email: evan.m.wall@gmail.com
disqus-id: disqy
headerimage: "/images/terminaltimes.png"
github_username: EvanWoah
markdown: kramdown
sass:
  style: :compressed
staticman:
  api: https://anasbasem.herokuapp.com/v2/entry/basemwahba/anas/master/comments
  path: _data/comments/test-slug
