# Site settings
title:        "Terminal Times"
description:  "An Open Comedy Publication"
baseurl:      "" # the subpath of your site, e.g. /blog/
url:          "http://terminaltimes.com" # the base hostname & protocol for your site
permalink:    /:year/:title
email:        "evan.m.wall@gmail.com"
disqus-id:    "" #leave blank if you dont want comments.
headerimage: "/images/terminaltimes.jpg"

# Build settings
markdown:     kramdown
sass:
    style: :compressed
